### ISSUE TITLE
Getting an error as I try to read or convert a .drk.

### ISSUE THREAD

**Issue by Diogo-Pedrosa** [ludovicb1239/Aim_2_MoTeC#2]
When attempting to read a .drk file, I encounter a System.NullReferenceException with the message 'Object reference not set to an instance of an object.' The exception occurs in the public static DateTimeStruct GetDateAndTime(int idx) method, specifically at the line DateTimeStruct dateTime = Marshal.PtrToStructure<DateTimeStruct>(dateTimePtr);.

Additionally, the error is accompanied by the message 'System.NullReferenceException' in the 'System.Private.CoreLib.dll'. When I try to debug the variables, I observe that every variable is set to 0.
![error,aimMotec](https://github.com/ludovicb1239/Aim_2_MoTeC/assets/79027251/9c659bf2-7be7-4088-9858-6a8829b667a4)

**Comment by ludovicb1239** [comment]
Hello,
Thanks for taking the time to write an issue with the proper debugging!
Because the convertion is running on another thread, the error might not be comming from where is told.
However, the read button also calls GetDateAndTime on main thread. I would suggest trying the read button first. If the error really happens at GetDateAndTime.
Additionally, I find very strange that you observe every variable is set to 0.
Have you tried using a release version with the latest .net6 ?

**Comment by ludovicb1239** [comment]
I'd also check if the previous information such as Vehicule name or Track name are working as they should.

**Comment by Diogo-Pedrosa** [comment]
I have reviewed the previous information, including the vehicle name, track, and they all show null when I debug. I have also noticed that the ID is 0, which I believe is causing the problem or at least is related to the problem. In the readButton function, everything seems to be working fine. Additionally, I have checked, and dateTimePtr in the GetDateAndTime function is also null.

I'm using dotnet\sdk\6.0.418.

I have also dowloaded MatLab Runtime 23.2.0.2459199 but it didint work as well.

**Comment by ludovicb1239** [comment]
If ID is 0, then something wrong is happening. I have found that using the "oldest" MatLab dll library worked everytime, and when I tried to update it to a newer version, I coulnd get it to work, sadly. Make sure the input directory path is right and has no spaces, might not be the problem but just in case. Also make sure that the running CPU is the right one, the same as the MatLab dll.

**Comment by ludovicb1239** [comment]
If ReadButton works, then all of the info in the file should be displayed on the UI. If the problem comes from converting only, then it might be because it's using another thread, but I didnt get such issue before.

**Comment by Diogo-Pedrosa** [comment]
The problem is that I can't seem to read any data. The read function crashes the app whenever it reaches the GetDateAndTime function. I tried changing the library name to the 2022 DLL, but it didn't even recognize it. Also, everything is happening in the same thread.

**Comment by ludovicb1239** [comment]
Hm thats strange. Is there any way I could try to read the data on my side ?

**Comment by Diogo-Pedrosa** [comment]
Here is the log that I'm attempting to read and convert. I've also tried another one, and it didn't work either. I suspect there might be an issue with my PC or something. It's in a zip file since I can't upload in .drk.
[LOG.zip](https://github.com/ludovicb1239/Aim_2_MoTeC/files/13905883/LOG.zip)

**Comment by ludovicb1239** [comment]
It seems the dll cant parse the file. Never had such an issue before, I'll look into it.

**Comment by ludovicb1239** [comment]
In my files used for testing, I found that the drk won't open by the dll if a rrk is not present. However, RS3 does open the drk without any worries.

**Comment by ludovicb1239** [comment]
Seems like RRK is linked to GPS data, thus making me thing that the dll only processes file with gps data. 
On another note, XRK files seem to work just as well if you have one of those..

**Comment by Diogo-Pedrosa** [comment]
So, is it the absence of GPS data that's causing the issue? We don't utilize GPS data because the GPS doesn't function in our AIM; we suspect it's a hardware problem. Is there a way to utilize the accelerometer to obtain this data? How difficult would it be to modify this DLL to effectively handle this data without relying on the GPS

**Comment by mitchdetailed** [comment]
> So, is it the absence of GPS data that's causing the issue? We don't utilize GPS data because the GPS doesn't function in our AIM; we suspect it's a hardware problem. Is there a way to utilize the accelerometer to obtain this data? How difficult would it be to modify this DLL to effectively handle this data without relying on the GPS

Its a DLL issue imo.

xrk cleanly parses into a pyarrow table for channel values.

drk does not.

my solution was to use the drk csv export in rs2 and use that for parsing to other file formats

**Comment by Diogo-Pedrosa** [comment]
> > So, is it the absence of GPS data that's causing the issue? We don't utilize GPS data because the GPS doesn't function in our AIM; we suspect it's a hardware problem. Is there a way to utilize the accelerometer to obtain this data? How difficult would it be to modify this DLL to effectively handle this data without relying on the GPS
> 
> Its a DLL issue imo.
> 
> xrk cleanly parses into a pyarrow table for channel values.
> 
> drk does not.
> 
> my solution was to use the drk csv export in rs2 and use that for parsing to other file formats

Yeah, I've managed to make it all work. I just adapted the code to get the data from the CSV that RS2 provides. Since my aim doesn't support XRK, I might stay with this solution.
